# Conexion a la base de datos mysql
spring.datasource.url=jdbc:mysql://localhost:3306/camara_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
!controla lo que se hace con tabla de la BD
spring.jpa.hibernate.ddl-auto=update
!se encarga de mostrar en consola lo que se ejecuta
spring.jpa.show-sql=true


# Servidor
server.port=8080

# Web
spring.web.resources.static-locations=file:uploads/

# Archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
